# -*- coding: utf-8 -*-
"""ano.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17f7CD7kyMA-FnzAhtA74T_URnwHw76GX
"""

nome = input("Digite seu nome: ")
nascimento = int(input("Digite seu ano de nascimento: "))
print("Sua idade em 2021 é de: ", 2021-nascimento)