# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q9YwDrtddnenqpX2_I-cc7Pf2cucMKor
"""

def calculadora(num1,num2,operacao):
   match operacao:
    case 1:
      return num1 + num2
    case 2:
      return num1 - num2
    case 3:
      return num1 * num2
    case 4:
      return num1 / num2
    case _:
      return 0

menu = """
1. Soma
2. Subtração
3. Multiplicação
4. Divisão
"""
print(menu)

opcao = int(input("Digite uma opção: "))
num1 = float(input("Digite um numero: "))
num2 = float(input("Digite outro numero: "))
print(calculadora(num1,num2,opcao))